name: 07 - Using Expressions

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
              type: boolean
              default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] Print start-up data'
              if: ${{ inputs.debug }}
              run: | 
                echo "Triggered by
                echo "Triggered by: ${{ github.event_name }}"
                echo "Branch: ${{ github.ref }}"
                echo "Commit SHA: ${{ github.sha }}"
                echo "Runner OS: ${{ runner.os }}"
            - name: '[debug] Print when triggered from main'
              if: ${{ inputs.debug && github.ref == '/home/runner/work/_temp/f8e376b1-bd7f-422d-8a7b-e5b95eddaab5.sh' }}
              run: echo " I was triggered from main"
            - name: Greeting
              run: echo "Hello, world"
